# In this project we will be working on the dataset for Doctor's Consultation Fee to analyze the data and create a model to predict the fees. 
The  focus will be on transforming the data to be able to work with it and create a working model.

In [1]:
#Importing the Libraries

import numpy as np
import pandas as pd
import seaborn as sns
from scipy import stats
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression

In [2]:
#read the csv files

df=pd.read_csv("Final_Train.csv")
test=pd.read_csv("Final_Test.csv")

Lets check the details on data to get some insights.

In [3]:
df.head()

,Qualification,Experience,Rating,Place,Profile,Miscellaneous_Info,Fees
0,"BHMS, MD - Homeopathy",24 years experience,100%,"Kakkanad, Ernakulam",Homeopath,"100% 16 Feedback Kakkanad, Ernakulam",100
1,"BAMS, MD - Ayurveda Medicine",12 years experience,98%,"Whitefield, Bangalore",Ayurveda,"98% 76 Feedback Whitefield, Bangalore",350
2,"MBBS, MS - Otorhinolaryngology",9 years experience,NaN,"Mathikere - BEL, Bangalore",ENT Specialist,NaN,300
3,"BSc - Zoology, BAMS",12 years experience,NaN,"Bannerghatta Road, Bangalore",Ayurveda,"Bannerghatta Road, Bangalore ₹250 Available on...",250
4,BAMS,20 years experience,100%,"Keelkattalai, Chennai",Ayurveda,"100% 4 Feedback Keelkattalai, Chennai",250

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5960 entries, 0 to 5959
Data columns (total 7 columns):
Qualification         5960 non-null object
Experience            5960 non-null object
Rating                2659 non-null object
Place                 5935 non-null object
Profile               5960 non-null object
Miscellaneous_Info    3341 non-null object
Fees                  5960 non-null int64
dtypes: int64(1), object(6)
memory usage: 326.0+ KB

In [5]:
df.describe()

              Fees
count  5960.000000
mean    307.954362
std     190.934916
min       5.000000
25%     150.000000
50%     300.000000
75%     500.000000
max     950.000000

As wee can see there are 6 object data type columns and one integer. We need to convert this data. 

Lets combine the test and train data to be used at a later stage for label encoding to avoid errors when working on model.

While looking at the data, we will also be working on data cleaning for both train and test dataset as applicable and required.

In [6]:
data = [df[['Qualification', 'Experience', 'Rating', 'Place', 'Profile', 'Miscellaneous_Info']], test]

data = pd.concat(data)

In [7]:
data.isnull().sum()

Qualification            0
Experience               0
Rating                4391
Place                   31
Profile                  0
Miscellaneous_Info    3453
dtype: int64

In [8]:
test.isnull().sum()

Qualification            0
Experience               0
Rating                1090
Place                    6
Profile                  0
Miscellaneous_Info     834
dtype: int64

There are null values in 3 columns and we need to work on them while cleaning the data.

Lets work on the Qualification column to find the maximum number of qualifications a person has and then split the qualification column into maximum number of qualifications a person has.

In [9]:

Qualification = list(data['Qualification'])

# Finding Maximum number of Qualification mentioned in a single cell
maxim = 1
for i in Qualification :
    if len(i.split(',')) > maxim:
         maxim = len(i.split(','))
         
print("\n\nMaximum Qualificaton in a Cell : ", maxim)

Maximum Qualificaton in a Cell :  17

In [10]:
all_qualification = []

for i in Qualification :
    if len(i.split(',')) == 1:
         all_qualification.append(i.split(',')[0].strip().upper())
    else :
        for it in range(len(i.split(','))):
            all_qualification.append(i.split(',')[it].strip().upper())

print("\n\nNumber of Unique Qualifications : ", len(pd.Series(all_qualification).unique()))
print("\n\nUnique Qualifications:\n", pd.Series(all_qualification).unique())

all_qualification = list(pd.Series(all_qualification).unique())

Number of Unique Qualifications :  898


Unique Qualifications:
 ['BHMS' 'MD - HOMEOPATHY' 'BAMS' 'MD - AYURVEDA MEDICINE' 'MBBS'
 'MS - OTORHINOLARYNGOLOGY' 'BSC - ZOOLOGY' 'BDS' 'MD - GENERAL MEDICINE'
 'BSC' 'MS' 'DNB - ENT' 'MDS' 'MDS - ORAL & MAXILLOFACIAL SURGERY'
 'DIPLOMA IN OTORHINOLARYNGOLOGY (DLO)' 'MF- HOMEOPATHY' 'MS - ENT' 'DNB'
 'FELLOWSHIP OF COLLEGE OF GENERAL PRACTICE (FCGP)' 'DDVL' 'IBCLC (USA)'
 'POST GRADUATE DIPLOMA IN DIABETOLOGY (PGDD)' 'DIPLOMA IN DERMATOLOGY'
 'FELLOWSHIP IN AESTHETIC MEDICINE' 'DM - NEUROLOGY' 'MD - PEDIATRICS'
 'FELLOWSHIP IN CLEFT LIP AND CRANIOFACIAL SURGERY'
 'DIPLOMA IN COSMETOLOGY' 'AFIH' 'MDS - PROSTHODONTIST AND CROWN BRIDGE'
 'M. D. HOM. (PRACTICE OF MEDICINE)' 'DIPLOMA IN EMERGENCY MEDICINE'
 'DIPLOMA IN COUNSELLING SKILLS'
 'DHMS (DIPLOMA IN HOMEOPATHIC MEDICINE AND SURGERY)' 'MD - DERMATOLOGY'
 'VENEREOLOGY & LEPROSY' 'MDS - ORAL AND MAXILLOFACIAL PATHOLOGY'
 'MFDS RCS' 'MRCS (UK)' 'FRGUHS'
 'FELLOWSHIP IN DERMATOLOGICAL LASER SURGERY'
 'MEMBER OF THE ROYAL COLLEGE OF PHYSICIANS' 'UK (MRCP UK)'
 'MNAMS- FAMILY MEDICINE' 'MD - MEDICINE' 'MS - PSYCHOLOGY'
 'DIPLOMA IN SKIN AESTHETICS' 'MDS - PERIODONTOLOGY AND ORAL IMPLANTOLOGY'
 'CERTIFICATE IN COSMETIC DENTISTRY'
 'POST GRADUATE CERTIFICATE IN ENDODONTICS (PGCE)'
 'FELLOW OF ACADEMY OF GENERAL EDUCATION (FAGE)' 'MD - RHEUMATOLOGY'
 'MDS - PAEDODONTICS AND PREVENTIVE DENTISTRY'
 'MDS-ORAL PATHOLOGY AND ORAL MICROBIOLOGY' 'FRCP'
 'DOCTOR OF SCIENCE (DSC.)' 'D.LITT - DIABETOLOGY' 'DDV'
 'MDS - CONSERVATIVE DENTISTRY & ENDODONTICS' 'FICD'
 'POST GRADUATE DIPLOMA IN EMERGENCY SERVICES (PGDEMS)'
 'GET INSPIRED BY REMARKABLE STORIES OF PEOPLE LIKE YOU'
 'MD - ACUPUNCTURE' 'MASTER OF HOSPITAL ADMINISTRATION' 'BA'
 'MDS - PERIODONTICS' 'PGD IN ENDODONTICS' 'MDS - PEDODONTICS'
 'PHD - ORTHODONTICS & DENTOFACIAL ORTHOPAEDICS' 'MORTH' 'MS - AYURVEDA'
 'MRCPS' 'P.G DIPLOMA IN AESTHETIC DENTISTRY'
 'MD - TUBERCULOSIS & RESPIRATORY DISEASES/MEDICINE'
 'MS - GENERAL SURGERY' 'DIPLOMA IN HEALTH ADMINISTRATION'
 'MD - SKIN & VD' 'FAMS - FELLOWSHIP OF THE ACADEMY MEDICINE'
 'MD - INTERNAL MEDICINE' 'DNB - INTERNAL MEDICINE'
 'FRCS - GENERAL SURGERY' 'PHD - HOMOEOPATHY'
 'CERTIFICATE IN DENTAL IMPLANTS'
 'MDS - ORTHODONTICS AND DENTOFACIAL ORTHOPAEDICS' 'DNB - FAMILY MEDICINE'
 'MS - PEDIATRIC'
 'MEMBER OF THE ROYAL SOCIETY FOR THE PROMOTION OF HEALTH (UK) (MRSH)'
 'POST GRADUATE DIPLOMA IN ENDOCRINOLOGY' 'MDS - PROSTHODONTICS'
 'M.SC.- CLINICAL NUTRITION AND DIETETICS'
 'MSC - PSYCHOTHERAPY AND COUNSELLING' 'MS (SHALYATANTRA)' 'MSC - YOGA'
 'DLO' 'POST GRADUATE DIPLOMA IN ADVANCED IMPLANTOLOGY'
 'MD - ALTERNATE MEDICINE'
 'POST GRADUATE DIPLOMA IN COUNSELLING & PSYCHOTHERAPY'
 'MS - COUNSELLING & PSYCHOTHERAPY' 'PHD - ALTERNATIVE MEDICINE'
 'FELLOWSHIP IN ORAL IMPLANTLOGY'
 'DIPLOMA IN PERSONAL COUNSELLING SKILLS (DPCS)' 'DNB - DERMATOLOGY'
 'GCEH' 'CERTIFICATION IN PERSONAL COUNSLING'
 'POST GRADUATE DIPLOMA IN HEALTHCARE MANAGEMENT(PGDHM)'
 'FELLOWSHIP IN LASERS & COSMETOLOGY'
 'FELLOWSHIP IN ANTI-AGING AND AESTHETIC MEDICINE'
 'DIPLOMA IN PRACTICAL DERMATOLOGY' 'FELLOW HAIR TRANSPLANT SURGERY'
 'FELLOWSHIP IN LASERS & ADVANCED DERMATOLOGY' 'DNB - PAEDIATRICS'
 'MRCPCH (UK)' 'MDS - ORAL MEDICINE AND RADIOLOGY'
 'DIPLOMA IN OBESITY MANAGEMNT' 'CERTIFICATE COURSE IN THERAPEUTIC YOGA'
 'DNB - NEPHROLOGY' 'CERTIFICATION IN AESTHETIC DENTISTRY' 'MRCP'
 'FELLOWSHIP IN LARYNGOLOGY BRONCHOESOPHAGOLOGY' 'FAGE'
 'DIPLOMA IN MEDICAL RADIO-DIAGNOSIS'
 'CERTIFICATION IN FULL MOUTH REHABILITATION' 'DIPLOMA IN ACUPUNCTURE'
 'DIPLOMA IN NATUROPATHY & YOGIC SCIENCE (DNYS)'
 'FELLOWSHIP IN MINIMAL ACCESS SURGERY' 'DGO'
 'DIPLOMATE IN ORAL IMPLANTOLOGY' 'MASTERS IN ORAL IMPLANTOLOGY'
 'IMPLANT EXTERNSHIP PROGRAM' 'FELLOWSHIP IN IMPLANTOLOGY'
 'M.S. (AYURVED) STRI ROGA & PRASUTI TANTRA'
 'MS - AYURVEDIC GYNECOLOGY & OBSTETRICS' 'MD - PATHOLOGY'
 'FELLOWSHIP IN RHEUMATOLOGY' 'MBA' 'D.Y.A' 'DVD'
 'DIPLOMA IN PUBLIC HEALTH' 'PHD- AYURVEDA' 'DM - CRITICAL CARE MEDICINE'
 'POST GRADUATE COURSE IN DIABETOLOGY' 'DNB - OTORHINOLARYNGOLOGY' 'BSAM'
 'CERTIFICATE COURSE IN SPORTS AND FITNESS NUTRITION'
 'DIPLOMA IN ADVANCED SKIN AND HAIR TREATMENTS'
 'DOCTOR OF MEDICINE (ALTERNATE MEDICINE)' 'CERTIFICATE IN COSMETOLOGY'
 'MD - SKIN' 'VD & LEPROSY' 'MDS - PUBLIC HEALTH DENTISTRY'
 'POST GRADUATE DIPLOMA IN YOGA' 'DIPLOMA IN ENT' 'MA' 'DNHE'
 'DIPLOMA IN ENDOSCOPY' 'DIPLOMA IN ANESTHESIOLOGY' 'MRCGP'
 'MDS - ORTHODONTICS' 'MD - MICROBIOLOGY'
 'POST-GRADUATE CERTIFICATE IN ORAL IMPLANTOLOGY (PGCOI)' 'DO'
 'DIPLOMA IN NATUROPATHY & YOGA (NDDY)' 'DNB - DERMATOLOGY & VENEREOLOGY'
 'DIPLOMA IN DERMATOLOGY & VENEROLOGY' 'DPM (PSYCHIATRY)'
 'M.D. (PSYCHIATRY)' 'MD - PHARMACOLOGY' 'DIPLOMA IN DIABETOLOGY'
 'FELLOWSHIP IN DIABETOLOGY(ROYAL LIVERPOOL UNIVERSITY HOSPITAL' 'UK)'
 'DIPLOMA IN FAMILY MEDICINE (DFM)'
 'POST GRADUATE DIPLOMA IN CLINICAL RESEARCH (PGDCR)' 'F.A.G.E'
 'DIPLOMA IN CLINICAL PANCHAKARMA' 'DIPLOMA IN CHILD HEALTH (DCH)'
 'DNB - PEDIATRICS' 'DAA - DIPLOMA IN ALLERGY ASTHMA AND IMMUNOLOGY'
 'MS - ENDOCRINOLOGY & DIABETES' 'DM - CARDIOLOGY'
 'FNB - INFECTIOUS DISEASE' 'DNB - GENERAL MEDICINE'
 'DIPLOMA IN TUBERCULOSIS AND CHEST DISEASES (DTCD)'
 'DIVISION OF CLINICAL PSYCHOLOGY (DCP)'
 'MSC - MASTER OF ORAL IMPLANTOLOGY (MOI)' 'MD - ONCOLOGY'
 'FCPS - DERMATOLOGY' 'CERTIFICATE IN CHILD HEALTH (CCH)'
 'MASTERS IN COUNSELLING AND PSYCHOTHERAPY' 'DIPLOMA IN RHEUMATOLOGY'
 'MCP(UCLA-USA)' 'PHD - NEUROPSYCHOLOGY' 'FELLOWSHIP IN ENT'
 'DIPLOMA IN NATUROPATHY (ND)' 'PG DIPLOMA IN SEXUAL MEDICINE'
 'DIPLOMA IN MEDICAL LAW AND ETHICS (PGDMLE)' 'MRCP (UK)'
 'MBA (HEALTH CARE)'
 'DIPLOMATE OF AMERICAN BOARD OF HAIR RESTORATION SURGERY'
 'POST GRADUATE DIPLOMA IN DIABETES' 'MNAMS - PLASTIC SURGERY'
 'CERTIFIED IN HAIR TRANSPLANTATION'
 'PG DIPLOMA IN CLINICAL COSMETOLOGY (PGDCC)' 'DORL (ENT)' 'IDCC (ISCCM)'
 'MD - FAMILY MEDICINE' 'MASTER OF PUBLIC HEALTH (MPH)'
 'DIPLOMA IN CARDIOLOGY' 'FELLOWSHIP IN COSMETIC DERMATOLOGY'
 'MD - ANAESTHESIOLOGY' 'AYURVEDIC PANCHKARMA'
 'POST GRADUATE DIPLOMA IN DERMOTOLOGY (PGDD)'
 'CERTIFICATE OF ORAL IMPLANTOLOGY' 'CERTIFICATION IN LASER DENTISTRY'
 "DIP' NMD" 'PGMHA' 'DIPLOMA IN HOSPITAL MANAGEMENT'
 'CERTIFICATE COURSE IN MANAGEMENT OF THYROID DISORDER'
 'FELLOWSHIP IN DIABETOLOGY(BOSTON SCHOOL OF MEDICINE' 'USA)' 'PGDHHM'
 'POST GRADUATE DIPLOMA IN HOSPITAL & HEALTHCARE MANAGEMENT' 'FCSI'
 'FSCAI' 'MASTER OF CLINICAL DENTISTRY' 'CERTIFIED IN PANCHKARMA'
 'CERTIFICATION IN YOGA' 'PAANCHABHAUTIC AYURVEDA CERTIFICATE'
 'DIPLOMA IN TRADITIONAL CHINESE MEDICINE'
 'DIPLOMA OF CLINICAL HYPNOTHERAPY' 'FELLOWSHIP IN DIABETOLOGY'
 'DIPLOMA IN LASER DENTISTRY'
 'DIPLOMA IN PREVENTIVE & PROMOTIVE HEALTHCARE'
 'INTEGRATED CLINICAL HYPNOTHERAPY' 'MASTER OF ORAL LASER APPLICATIONS'
 'MSC - PSYCHOLOGY' 'POST GRADUATE DIPLOMA IN FAMILY MEDICINE (PGDFM)'
 'MD - AYURVEDIC PHARMACOLOGY' 'CERTIFICATE ENDODONTICS & PEDODONTICS'
 'CERTIFIED INMAN ALIGNER' '39 YEARS EXPERIENCE' 'CERT. (PROSTHODONTICS)'
 'MD - AYURVEDIC OBSTETRICS AND GYNECOLOGY'
 'DIPLOMA IN HOSPITAL ADMINISTRATION' 'MCH - UROLOGY'
 'DNB - UROLOGY/GENITO - URINARY SURGERY' 'FRCP - ENDOCRINOLOGY' 'LCEH'
 'NUTRITION CERTIFICATION' 'DOCTOR OF HOMEOPATHIC MEDICINE (HMD)'
 'DIPLOMA IN IMPLANT DENTISTRY' 'FELLOWSHIP IN COSMETOLOGY'
 'MD - COMMUNITY MEDICINE' 'P.G.HOM.(LONDON)'
 'FELLOWSHIP IN MEDICAL COSMETOLOGY' 'GERMANY'
 'CERTIFIED ADVANCE COURSE IN ENDODONTICS'
 'DIPLOMATE OF NATIONAL BOARD EXAM' 'DIPLOMA IN IMPLANTHOLOGY'
 'ECFMG (USA)' 'FELLOWSHIP IN DERMATOSURGERY'
 'FELLOWSHIP IN PEDIATRIC DERMATOLOGY' 'CGO'
 'DIPLOMA IN TRICHOLOGY - COSMETOLOGY' 'DIPLOMA IN WEIGHT LOSS'
 'EDUCATIONDIPLOMA IN NATUROPATHY AND YOGA'
 'P.G DIPLOMA IN DIABETES MANAGEMENT'
 'POST GRADUATE DIPLOMA IN MATERNITY AND CHILD HEALTH (PGDMCH)'
 'FELLOWSHIP SIB' 'DAA' 'DNB - PERIPHERAL VASCULAR SURGERY' 'FRACS'
 'DIPLOMA IN AESTHETIC MEDICINE' 'MCIP' 'PGDCFS' 'PGDFOS'
 'DIPLOMA IN JOURNALISM' 'MD - HOMOEOPATHIC PHILOSOPHY'
 'MS - COUNSELLING AND PSYCHOTHERAPY' 'MCH - ONCOLOGY'
 'MNAMS - GENERAL SURGERY' 'DIPLOMA IN GERIATRIC MEDICINE' 'M C P S'
 'FELLOWSHIP IN INFECTIOUS DISEASE' 'M DERM'
 'FCAH (FELLOW SHIP COURSE IN ADVANCE HOMOEPATH)'
 'MD - PULMONARY MEDICINE' 'BPTH/BPT' 'PGNAHI' 'CSD' 'MSC'
 'PG IN DIABETOLOGY' 'FCPS SKIN & VD' 'M. D. IN KAYACHIKISTA'
 'DIPLOMA IN PSYCHIATRY' 'DIPLOMA IN PANCHKARMA CHIKITSA'
 'FELLOWSHIP AND DIPLOMATE IN IMPLANTOLOGY FROM ICOI (USA)'
 'MCH - PLASTIC SURGERY' 'FELLOWSHIP IN CLEFT LIP & PALATE'
 'MD - DIABETOLOGY' 'POST DOCTORAL FELLOWSHIP IN DIABETOLOGY'
 'MD - CARDIOLOGY' 'MBA (HCS)' 'FFDRCSI'
 'FELLOWSHIP IN APPLIED NUTRITION(FAN)'
 'PHD - CLINICAL NEUROSCIENCE (PEDIATRICS)'
 'PROFESSIONAL DIPLOMA IN CLINICAL RESEARCH (PDCR)' 'FICOI'
 'MD - PHYSICIAN' 'BNYS'
 'ADVANCED CERTIFICATE COURSE IN AESTHETIC DENTISTRY'
 'PROFESSIONAL IMPLANTOLOGY TRAINING COURSE (PITC)' 'FAGE- FELLOW'
 'COMPREHENSIVE COURSE IN MODERN ENDODONTICS'
 'INDIAN DIPLOMA CRITICAL CARE MEDICINE (IDCCM)'
 'FELLOWSHIP IN AESTHETIC DENTISTRY (FAD)'
 'FELLOWSHIP IN RHINOLOGY AND ENDOSCOPIC SKULL BASE SURGERY'
 'FELLOWSHIP IN OTOLOGY AND NEUROTOLOGY'
 'FELLOW OF INTERNATIONAL CONGRESS OF ORAL IMPLANTOLOGIST'
 'POST MD SR AIIMS' 'FELLOWSHIP IN HEAD & NECK ONCOLOGY SURGERY'
 'CERTIFICATE IN DENTAL IMPLANTOLOGY' 'CERTIFICATE IN ORTHODONTICS'
 'BACHELOR OF CHIROPRACTIC' 'DIPLOMA IN VENEREOLOGY'
 'CERTIFICATE IN INVISIBLE BRACES' 'CERTIFICATION IN CLEAR ALIGNERS'
 'CERTIFICATION IN “PREVENTING CHRONIC PAIN: A HUMAN SYSTEMS APPROACH”'
 'CERTIFICATION IN “VITAL SIGNS: UNDERSTANDING WHAT THE BODY IS TELLING US”'
 'DIPLOMA IN MEDICAL TRICHOLOGY' 'B.SC' 'MBA - HEALTHCARE ADMINISTRATION'
 'MRCPSYCH' 'DIPLOMA IN MEDICAL COSMETOLOGY AND AESTHETIC MEDICINE'
 'PG DIPLOMA IN HEALTH & HOSPITAL MANAGEMENT'
 'PG DIPLOMA IN MEDICAL TOURISM' 'FELLOWSHIP IN LASERS & AESTHETICS'
 'DIPLOMA IN ORTHOPAEDICS' 'DNB - GENERAL SURGERY'
 'MS - PAEDIATRICS SURGERY' 'DNB - PEDIATRIC SURGERY'
 'ONE YEAR CERTIFICATE COURSE IN HOSPITAL MANAGEMENT'
 'CERTIFIED COURSE IN YOGA' 'DICOI' 'MBA - HOSPITAL MANAGEMENT' 'G.A.M.S'
 'MS - OPHTHALMOLOGY' 'FELLOWSHIP IN IMPLANT AND ESTHETIC DENTISTRY'
 'AOC IN AESTHETIC DENTISTRY' 'PGDE (COSMETIC & ESTHETIC DENTIST)'
 'INVISALIGN TRAINING COURSE'
 'POST GRADUATE DIPLOMA IN CLINICAL NUTRITION & DIETETICS'
 'MASTERS DIPLOMA IN ACUPRESSURE' 'MDS- ORAL PATHOLOGY'
 'FELLOWSHIP IN BREAST SURGERY'
 'FELLOWSHIP IN NON-INVASIVE CARDIOLOGY (FIC)' 'MAMS'
 'FCPS - MID. & GYNAE' 'CVD' 'DIPLOMA IN CLINICAL NUTRITION'
 'MS - AYURVEDIC GENERAL SURGERY' 'MD - YOGA AND REHAB'
 'CERTIFICATION IN INFECTIOUS DISEASES'
 'DIPLOMA IN TROPICAL MEDICINE HEALTH' 'FELLOWSHIP IN SKULL BASE SURGERY'
 'TFO (USA)' 'PG IN DIABETOLOGY (USA)'
 'MDS - ORTHODONTICS AND OROFACIAL ORTHOPAEDICS'
 'M.MED IN FAMILY MEDICINE' 'DIACH(GREECE)'
 'CERTIFICATE COURSE IN ADVANCED HOMOEOPATHY (C.C.A.H)' 'FCCM'
 'FCCP - PULMONARY MEDICINE'
 'DIPLOMA OF THE FACULTY OF FAMILY PLANNING (DFFP)'
 'DIPLOMA IN SPORTS THERAPY'
 'POST GRADUATE DIPLOMA IN HOSPITAL MANAGEMENT'
 'CERTIFICATION FOR PROFESSIONAL CHEMICAL PEEL WORKSHOP'
 'CERTIFICATE IN AESTHETIC MEDICINE' 'BUMS'
 'MASTERS IN CLINICAL DERMATOLOGY' 'PGCC - RHEUMATOLOGY'
 'MD - OPTHALMOLOGY' 'MD - KAYACHIKITSALAYA' 'MS - IMPLANTOLGY'
 'IMPLANTOLOGY ICOI(USA)' 'DIPLOMA IN DIET AND NUTRITION' 'PGDHA'
 'CERTIFICATE COURSE IN TUBERCULOSIS & CHEST DISEASES'
 'ADVANCED TRAINING PROGRAM IN DIABETES CARE'
 'PHD IN LIBERAL STUDIES IN DIABETOLOGY (TRINITY COLLEGE)' 'CCEDM' 'CCMTD'
 'CCDR' 'MDS - IMPLANTOLOGY' 'MD - OBSTETRICS & GYNAECOLOGY' 'MD-DVL'
 'DIPLOMA IN BEAUTY THERAPY'
 'CERTIFICATE COURSE IN COSMETIC DERMATOLOGY & LASERS'
 'PG DIPLOMA IN TRICHOLOGY' 'CERTIFICATE IN BOTOX' 'FILLERS' 'THREADLIFTS'
 'ADVANCED CERTIFICATION IN CLINICAL DIABETOLOGY' 'SCE DERMATOLOGY (RCP'
 'POST GRADUATE DIPLOMA IN ORTHODONTICS' 'CCD (DIABETOLOGY)'
 'MCH - CARDIO THORACIC AND VASCULAR SURGERY' 'DM - GASTROENTEROLOGY'
 'FCPS - GENERAL SURGERY' 'DM - RHEUMATOLOGY' 'FELLOWSHIP IN DERMATOLOGY'
 'TRAINING IN FACIAL AESTHETICS' 'CERTIFICATE IN HEALTH MANAGEMENT'
 'MD - HOMEOPATHY PSYCHIATRY' 'PGCAD' 'MRCP (PAED)'
 'DIPLOMATE AMERICAN ACADEMY OF AESTHETIC MEDICNE' 'MS - UROLOGY'
 'MCH - UROLOGY/GENITO-URINARY SURGERY'
 'PG DIPLOMA IN EMERGENCY TRAUMA CARE'
 'POST GRADUATE DIPLOMA IN DIABETOLOGY (PGDD)(MIDDLESEX UNIVERSITY'
 'FELLOWSHIP IN ORTHOPAEDIC REHABILITATION (FOR)' 'MIDA'
 'CERTIFICATE COURSE IN DENTAL LASERS'
 'CERTIFICATE COURSE IN IMPLANTOLOGY' 'DM - ENDOCRINOLOGY' 'PGCR'
 'DIPLOMA IN DIABETES/ENDOCRINOLOGY (MIDDLESEX UNIVERSITY)'
 'MD - PAEDIATRICS' 'MD - (DERMATOLOGY & STD)'
 'DIPLOMA IN CLINICAL PATHOLOGY'
 'PG DIPLOMA IN PREVENTIVE AND PROMOTIVE HEALTH CARE (PGD PPHC)'
 'FELLOWSHIP IN MEDICAL COSMETOLOGY (FMC)' 'MDS - ENDODONTICS'
 'MCH - NEURO SURGERY' 'FELLOWSHIP IN COSMETIC SURGERY'
 'DNB - OPHTHALMOLOGY' 'FELLOWSHIP IN VITREO-RETINA' 'MS - ORTHOPAEDICS'
 'MNAMS (MEMBERSHIP OF THE NATIONAL ACADEMY)'
 'POST GRADUATE DIPLOMA IN MEDICOLOGICAL SYSTEMS (PGDMS)'
 'FELLOW OF THE ROYAL AUSTRALASIAN COLLEGE OF SURGEONS'
 'FRACS (GENERAL SURGERY)' 'FELLOWSHIP IN AYURVEDIC MEDICINE'
 'DM - ONCOLOGY' 'DHMS' 'FELLOWSHIP IN ENDOCRINOLOGY'
 'DIABETES & METABOLISM'
 'FELLOW OF AMERICAN COLLEGE OF ENDOCRINOLOGY(FACE)'
 'PG DIPLOMA IN CHILD HEALTH' 'POST GRADUATE IN HOMOEOPATHY'
 'CERTIFIED IN ORTHODONTICS' 'CERTIFIED BPS DENTIST'
 'FELLOWSHIP IN ADVANCED ENDOSCOPIC SINUS SURGERY'
 'DEGREE IN DENTAL IMPLANT' 'ADVANCED ENDOTONTIC COURSE ON ROOT CANAL'
 'MASTER IN COUNSELLING PSYCHOLOGY'
 'DIPLOMA IN DIABETOLOGY (MUMBAI UNIVERSITY)' 'D.SC'
 'CERTIFICATION COURSE IN DIABETES' 'FELLOWSHIP IN CLINICAL CARDIOLOGY'
 'POST GRADUATE CERTIFICATE IN ADVANCED ORAL IMPLANTOLOGY'
 'PH.D PANCHAKARMA' 'M.CH' 'FICS' 'FRCS' 'PG DIPLOMA IN PANCHAKARMA'
 'F.C.I.P' 'MDS - ORAL & MAXILLOFACIAL PATHOLOGY AND MICROBIOLOGY'
 'M.CH - ORTHOPAEDICS' 'FELLOWSHIP IN JOINT REPLACEMENT'
 'FELLOWSHIP IN DIABETOLOGY(ROYAL LIVERPOOL ACADEMY' 'FCD - DIABETOLOGY'
 'PHD - MICROBIOLOGY' 'DEMS'
 'MEMBER OF ROYAL COLLEGE OF EMERGENCY MEDICINE(MRCEM)'
 'MASTERS IN EMERGENCY MEDICINE'
 'INTERNATIONAL CERTIFICATE IN IMPLANT DENTISTRY'
 'CURRENT CONCEPTS IN AMERICAN DENTISTRY ADVANCES IN IMPLANTOLOGY AND ORAL REHABILITATION'
 'MSC - FORENSIC ODONTOLOGY' 'MBA - HOSPITAL ADMINISTRATION'
 'MCH - SURGICAL GASTROENTEROLOGY/G.I. SURGERY' 'DNB - INFECTIOUS DISEASE'
 'PGDMLS' 'MBA - HEALTHCARE MANAGEMENT' 'M.H.SC-DIABETOLOGY' 'CCEBDM'
 'CERTIFICATE COURSE IN NUTRITION AND DIETETICS' 'PHD - ACUPUNCTURE'
 'BEMS' 'FELLOWSHIP IN GASTROENTEROLOGY'
 'DNB - ORAL & MAXILLOFACIAL SURGERY' 'MD- DRAVYA GUNA'
 'FELLOW OF ADVANCED MICRO EAR SURGERY'
 'MDS- PERIODONTIST & IMPLANTALOGIST' 'FELLOWSHIP IN HEAD & NECK SURGERY'
 'FELLOWSHIP TRAINING IN INTENSIVE CARE MEDICINE'
 'FELLOW OF INDIAN COLLEGE OF CARDIOLOGY (FICC)' 'MD - ANATOMY'
 'FELLOWSHIP IN CHILD AND ADOLESCENT PSYCHIATRY'
 'POST GRADUATE DIPLOMA IN PERIODONTICS AND IMPLANTOLOGY'
 'FELLOWSHIP PROGRAM IN FORENSIC ODONTOLOGY' 'FELLOWSHIP IN PHONOSURGERY'
 'MA - PSYCHOLOGY' 'POST GRADUATE COURSE IN RHEUMATOLOGY'
 'MD - VENEREOLOGY' 'MD - REPERTORY' 'DNB - OBSTETRICS & GYNECOLOGY'
 'POSTGRADUATE DIPLOMA CLINICAL CARDIOLOGY (PGDCC)'
 'FELLOWSHIP IN CARDIAC REHABILITATION'
 'CERTIFICATE COURSE IN ORAL IMPLANTOLOGY' 'MPH'
 'POST GRADUATE DIPLOMA IN HOLISTIC HEALTHCARE'
 'GRADUATE DIPLOMA IN FAMILY MEDICINE' 'SINGAPORE'
 'D.ORTHO FELLOW ARTHROSCOPY & ARTHROPLASTY(AUST)'
 'DNB - ORTHOPEDICS/ORTHOPEDIC SURGERY' 'MNAMS - DERMATOLOGY'
 'BASIC LIFE SUPPORT (BLS)' 'ACLS' 'ADVANCED TRAUMA LIFE SUPPORT (ATLS)'
 'DIPLOMA IN PHARMACY' 'ADVANCE DIPLOMA IN NUTRITION AND DIETETICS'
 'CERTIFICATE IN YOGA & MEDITATION' 'DM - NEPHROLOGY'
 'DIPLOMA IN NUTRITION AND HEALTH EDUCATION' 'MSC - CLINICAL DERMATOLOGY'
 'ADVANCED CERTIFICATE IN ENDODONTICS AND ESTHETICS'
 'ADVANCED CERTIFICATE COURSE IN DENTAL IMPLANTS' 'B.AC' 'FACC'
 'CERTIFICATE COURSE IN POSITIVE PSYCHOLOGY'
 'CLINICAL NUTRITIONIST CERTIFCATE'
 'M.SC - COUNSELLING AND FAMILY THERAPY' 'D. DERMATOLOGY (AY.)'
 'MASTER OF FAMILY MEDICINE' 'MS - OBSTETRICS & GYNAECOLOGY'
 'MDS- ROOT CANAL SPECIALIST' 'FCPS (ENT)' 'CERTIFICATE IN IMPLANTOLOGY'
 'FCPS - OTO-RHINO-LARYNGOLOGY'
 'CERTIFICATE IN MEDICAL COSMETOLOGY AND AESTHETICS'
 'MCH - HEAD AND NECK ONCOLOGY' 'DDVCPS' 'DIPLOMA IN MEDICAL COSMETOLOGY'
 'FNB - CRITICAL CARE MEDICINE'
 'EUROPEAN DIPLOMA IN INTENSIVE CARE MEDICINE (EDIC)'
 'CCST - INTERNAL MEDICINE' 'CCST - DIABETES & ENDOCRINOLOGY' 'M.D. (E.H)'
 'MDS - PREVENTIVE & COMMUNITY DENTISTRY'
 'DIPLOMA IN HOMOEOPATHY AND BIOCHEMISTRY'
 'DIPLOMA IN HAIR RESTORATION SURGERY'
 'FELLOWSHIP IN PEDIATRIC OTOLARYNGOLOGY'
 'FELLOWSHIP IN DIABETOLOGY(THE UNIVERSITY OF LIVERPOOL'
 'DIPLOMA IN INDUSTRIAL HYGIENE' 'DIPLOMA IN EDUCATIONAL PSYCHOLOGY'
 'CERTIFICATE IN FOOD AND NUTRITION'
 'DIPLOMA IN CLINICAL DERMATOLOGY (UK)' 'F.S.R.H' 'FCPS - MEDICINE'
 'MD - NEPHROLOGY' 'MCH - SURGICAL ONCOLOGY'
 'DIPLOMA IN GYNAECOLOGY & OBSTETRICS'
 'FELLOW OF THE AMERICAN ACADEMY OF DERMATOLOGY (FAAD)'
 'MDS - PROSTHODONTIST & ORAL IMPLANTOLOGIST' 'MD - HOMEO ORGANON'
 'MFGDP - MEMBERSHIP OF THE FACULTY OF GENERAL DENTAL PRACTITIONERS'
 'MEMBERSHIP OF THE FACULTY OF DENTAL SURGEONS(MFDS)'
 'DNB - RESPIRATORY DISEASES' 'BIMS' 'MCPS'
 'CERTIFICATE IN SPORTS NUTRITION'
 'POST GRADUATE DIPLOMA IN MEDICAL COSMETOLOGY (PGDMC)'
 'CERTIFICATE IN PEDIATRIC OTOLARYNGOLOGY - HEAD AND NECK SURGERY'
 'DIPLOMA IN AESTHETIC DERMATOLOGY' 'MD - INFECTIOUS DISEASES'
 'CERTIFICATE COURSE OF ONE YEAR IN DENTAL IMPLANTS'
 'CERTIFICATE COURSE IN ADVANCE IMPLANTOLOGY'
 'CERTIFICATE COURSE IN EVIDENCE BASED DIABETES MANAGEMENT (CCEBDM)'
 'CERTIFICATE COURSE IN GESTATIONAL DIABETES (CCGDM)'
 'MD - PHYSICAL MEDICINE & REHABILITATION'
 'DIPLOMA IN PHYSICAL MEDICINE & REHABILITATION'
 'FELLOWSHIP IN DIABETOLOGY & ENDOCRINOLOGY'
 'CCT - ENDOCRINOLOGY AND DIABETES MELLITUS'
 'CERTIFIED SINUS LIFT SURGEON' 'DIPLOMA IN SKIN POLISHING TECHNOLOGY'
 'DIPLOMA IN SLIMMING & LASER TREATMENTS'
 'CERTIFICATE IN CLINICAL COSMETOLOGY' 'PCAD (USA)' 'MD - ACUPRESSURE'
 'PHD - DIABETES' 'DIPLOMA IN COSMETIC DENTISTRY' 'FRCS - OTOLARYNGOLOGY'
 'DNB - CARDIOLOGY' 'DISTANCE FELLOWSHIP IN DIABETES MANAGEMENT'
 'MBA - HEALTHCARE SERVICES'
 'POST GRADUATE DIPLOMA IN DIABETOLOGY (PGDD)(JOHNS HOPKINS UNIVERSITY SCHOOL OF MEDICINE'
 'FELLOWSHIP IN DIABETOLOGY(JOHNS HOPKINS UNIVERSITY SCHOOL OF MEDICINE'
 'DMD - DOCTOR OF DENTAL MEDICINE'
 'POST GRADUATE DIPLOMA IN DIABETOLOGY (PGDD)(CARDIFF UNIVERSITY' 'ACDMC'
 'DIPLOMA IN ACUPRESSURE THERAPY'
 'ADVANCED CERTIFICATE COURSE IN DIABETES'
 'POST GRADUATE CERTIFICATE IN SPORTS MEDICINE'
 'CLINICAL CARDIOLOGY CERTIFICATION' 'FDS SURGICAL ORAL ONCOLOGY'
 'DIPLOMA IN ULTRA SONOLOGY' 'MD (HOM) - PAEDITRICS'
 'CLINICAL FELLOWSHIP IN RHINOLOGY' 'MD - OPHTHALMOLOGY'
 'MDS - ORAL PATHALOGY & MICROBIOLOGY' 'LLB' 'FELLOW IN DERMATO - SURGERY'
 'ADVANCE FELLOWSHIP IN LASER & DERMATOSURGERY' 'PHD - PSYCHOLOGY'
 'MD - TUBERCULOSIS & RESPIRATORY DISEASES / PULMONARY MEDICINE'
 'MDS - ORAL MEDICINE'
 'PG CERTIFICATE COURSE IN DIABETES EDUCATION(PGDCE)' 'PGD YOGA'
 'MA (YOGA SHASTRA)' 'DIPLOMA IN YOGA SHIKSHAKA'
 "YOGA INSTRUCTOR'S COURSE" 'D.H.M' 'MD - PHYSIOLOGY' 'F.A.M'
 'FELLOWSHIP IN LARYNGOLOGY' 'PH. D - ENT'
 'CERTIFICATE IN LASER AND DERMATOLOGY'
 'DIPLOMA IN SKIN & VINEREAL DISEASE'
 'DIPLOMA OF NUTRITION & DIET PLANNING' 'DIPLOMA IN DIABETES'
 'PG - ECHOCARDIOGRAPHY'
 'DM - PULMONARY MEDICINE & CRITICAL CARE MEDICINE'
 'EUROPEAN DIPLOMA IN RESPIRATORY MEDICINE'
 'POST GRADUATE DIPLOMA IN DIABETIC EDUCATION'
 'WEIGHT MANAGEMENT CONSULTANT CERTIFICATE'
 'FELLOWSHIP (ENDOSCOPIC SINUS SURGERY)' 'MD - TB & CHEST'
 'FRACP (RHEUMATOLOGY)' 'F.C.P.S (DERMATOLOGY)'
 'POST GRADUATE DIPLOMA IN HEALTH SCIENCES (PGDHSC)'
 'MASTER OF HEALTH SCIENCES (MHSC)' 'M. SC IN YOGA'
 'DIPLOMA IN NATUROPATHY & YOGIC SCIENCE (DNYT)' 'DYSC.'
 'POST GRADUATE IN CLINICAL PSYCHOLOGY'
 'CERTIFICATE COURSE IN PANCHAKARMA' 'CERTIFICATE COURSE IN NADI SUTRA'

In [11]:
Qualification = list(df['Qualification'])

Q1 = []
Q2 = []
Q3 = []
Q4 = []
Q5 = []
Q6 = []
Q7 = []
Q8 = []
Q9 = []
Q10 = []
Q11 = []
Q12 = []
Q13 = []
Q14 = []
Q15 = []
Q16 = []
Q17 = []


for i in Qualification:
        try :
            Q1.append(i.split(',')[0].strip().upper())
        except :
            Q1.append('NONE')
        try :
            Q2.append(i.split(',')[1].strip().upper())
        except :
            Q2.append('NONE')
        try :
            Q3.append(i.split(',')[2].strip().upper())
        except :
            Q3.append('NONE')
        try :
            Q4.append(i.split(',')[3].strip().upper())
        except :
            Q4.append('NONE')
        try :
            Q5.append(i.split(',')[4].strip().upper())
        except :
            Q5.append('NONE')
        try :
            Q6.append(i.split(',')[5].strip().upper())
        except :
            Q6.append('NONE')
        try :
            Q7.append(i.split(',')[6].strip().upper())
        except :
            Q7.append('NONE')
        try :
            Q8.append(i.split(',')[7].strip().upper())
        except :
            Q8.append('NONE')
        try :
            Q9.append(i.split(',')[8].strip().upper())
        except :
            Q9.append('NONE')    
        try :
            Q10.append(i.split(',')[9].strip().upper())
        except :
            Q10.append('NONE')
        try :
            Q11.append(i.split(',')[10].strip().upper())
        except :
            Q11.append('NONE')
        try :
            Q12.append(i.split(',')[11].strip().upper())
        except :
            Q12.append('NONE')
        try :
            Q13.append(i.split(',')[12].strip().upper())
        except :
            Q13.append('NONE')
        try :
            Q14.append(i.split(',')[13].strip().upper())
        except :
            Q14.append('NONE')
        try :
            Q15.append(i.split(',')[14].strip().upper())
        except :
            Q15.append('NONE')
        try :
            Q16.append(i.split(',')[15].strip().upper())
        except :
            Q16.append('NONE')
        try :
            Q17.append(i.split(',')[16].strip().upper())
        except :
            Q17.append('NONE')

In [12]:
# appending NONE to Unique qualification list
all_qualification.append('NONE')

Lets work on the Places column. This column has two pieces of information - locality and city. Lets split the Places column into two columns - Locality, City.

In [13]:
all_places = list(data['Place'])

for i in range(len(all_places)):
    if type(all_places[i]) == float:
        all_places[i] = 'NOT AVAILABLE'
    all_places[i] = all_places[i].strip().upper()
    
maxim = 1
for i in all_places :
    if len(i.split(',')) > maxim:
         maxim = len(i.split(','))
         
print("\n\nMaximum places in a Cell : ", maxim) 
print("\n\nNumber of Unique places (Including NOT AVAILABLE): ", len(pd.Series(all_places).unique()))
print("\n\nUnique Places:\n", pd.Series(all_places).unique())
 
all_places = list(pd.Series(all_places).unique())

Maximum places in a Cell :  2


Number of Unique places (Including NOT AVAILABLE):  948


Unique Places:
 ['KAKKANAD, ERNAKULAM' 'WHITEFIELD, BANGALORE'
 'MATHIKERE - BEL, BANGALORE' 'BANNERGHATTA ROAD, BANGALORE'
 'KEELKATTALAI, CHENNAI' 'PORUR, CHENNAI' 'KAROL BAGH, DELHI'
 'AREKERE, BANGALORE' 'OLD CITY, HYDERABAD' 'ATHANI, ERNAKULAM'
 'THOUSAND LIGHTS, CHENNAI' 'SOMAJIGUDA, HYDERABAD'
 'COIMBATORE RACECOURSE, COIMBATORE' 'JUBILEE HILLS, HYDERABAD'
 'KONDLI, DELHI' 'SAROOR NAGAR, HYDERABAD' 'TAMBARAM WEST, CHENNAI'
 'PURASAWAKKAM, CHENNAI' 'KPHB, HYDERABAD' 'HSR LAYOUT, BANGALORE'
 'POLLACHI, COIMBATORE' 'VASUNDHRA ENCLAVE, DELHI' 'CHEMBUR, MUMBAI'
 'THAMMANAM, ERNAKULAM' 'ANDHERI, MUMBAI' 'PATTOM, THIRUVANANTHAPURAM'
 'KUKATPALLY, HYDERABAD' 'VADAVALLI, COIMBATORE' 'DEFENCE COLONY, DELHI'
 'BANJARA HILLS, HYDERABAD' 'SION WEST, MUMBAI' 'CR PARK, DELHI'
 'MOGAPPAIR EAST, CHENNAI' 'IP EXTENSION, DELHI'
 'SAFDARJUNG ENCLAVE, DELHI' 'NEW FRIENDS COLONY, DELHI'
 'BORIVALI WEST, MUMBAI' 'SAKET, DELHI' 'MALAD, MUMBAI'
 'HYDER NAGAR, HYDERABAD' 'DAHISAR WEST, MUMBAI' 'RT NAGAR, BANGALORE'
 'POWAI, MUMBAI' 'BASHEERBAGH, HYDERABAD' 'MUSHEERABAD, HYDERABAD'
 'AS RAO NAGAR, HYDERABAD' 'MADHAPUR, HYDERABAD' 'GANDHINAGAR, HYDERABAD'
 'CHETPET, CHENNAI' 'VILEPARLE EAST, MUMBAI'
 'YELAHANKA NEW TOWN, BANGALORE' 'KODAMBAKKAM, CHENNAI'
 'MALLESWARAM, BANGALORE' 'PALLIKARANAI, CHENNAI' 'NALLAKUNTA, HYDERABAD'
 'PASCHIM VIHAR, DELHI' 'MEERA BAGH, DELHI' 'CHATTARPUR, DELHI'
 'ANDHERI WEST, MUMBAI' 'HIMAYAT NAGAR, HYDERABAD' 'ADAMBAKKAM, CHENNAI'
 'PUNJABI BAGH, DELHI' 'MAHALAXMI, MUMBAI' 'KALINA, MUMBAI'
 'ATTAPUR, HYDERABAD' 'LAKDIKAPUL, HYDERABAD' 'AMBATTUR, CHENNAI'
 'RAMNAGAR, COIMBATORE' 'SHALIMAR BAGH, DELHI' 'NUNGAMBAKKAM, CHENNAI'
 'MIYAPUR, HYDERABAD' 'SAGARPUR, DELHI' 'GIRGAON, MUMBAI'
 'JAYANAGAR, BANGALORE' 'PALAYAM, THIRUVANANTHAPURAM' 'MUNIRKA, DELHI'
 'TUGLAKABAD, DELHI' 'MOOSARAMBAGH, HYDERABAD' 'NOT AVAILABLE'
 'ANNA NAGAR EAST, CHENNAI' 'BANDRA WEST, MUMBAI'
 'KANAKPURA ROAD, BANGALORE' 'GREEN PARK, DELHI' 'MADURAVOYAL, CHENNAI'
 'DAHISAR EAST, MUMBAI' 'MOOSAPET, HYDERABAD' 'KORAMANGALA, BANGALORE'
 'TV MEDICAL COLLEGE, THIRUVANANTHAPURAM' 'KADAVANTHRA, ERNAKULAM'
 'GREAMS ROAD, CHENNAI' 'BOMMANAHALLI, BANGALORE' 'T NAGAR, CHENNAI'
 'YELAHANKA, BANGALORE' 'HAZRAT NIZAMUDDIN, DELHI'
 'OLD RAJENDRA NAGAR, DELHI' 'DADAR WEST, MUMBAI' 'INDIRANAGAR, BANGALORE'
 'PERUMBAKKAM, CHENNAI' 'SHAIKPET, HYDERABAD' 'VYTTILA, ERNAKULAM'
 'KHAR WEST, MUMBAI' 'GOREGAON WEST, MUMBAI' 'BAKKARWALA, DELHI'
 'NESAPAKKAM, CHENNAI' 'BTM LAYOUT 2ND STAGE, BANGALORE'
 'ASHOK NAGAR, CHENNAI' 'CHANDIVALI, MUMBAI' 'UTTAM NAGAR, DELHI'
 'GUJRANWALA TOWN, DELHI' 'GREATER KAILASH PART 1, DELHI'
 'PANCHSHEEL PARK, DELHI' 'THORAIPAKKAM, CHENNAI'
 'SOUTH EXTENSION 2, DELHI' 'KANDIVALI EAST, MUMBAI' 'PITAMPURA, DELHI'
 'BANASHANKARI 3RD STAGE, BANGALORE' 'KOLENCHERY, ERNAKULAM'
 'KUMARASWAMY LAYOUT, BANGALORE' 'VADAPALANI, CHENNAI'
 'MANIKONDA, HYDERABAD' 'GANDHIPURAM, COIMBATORE'
 'YESHWANTHPUR, BANGALORE' 'AYANAVARAM, CHENNAI'
 'BASAVESHWARANAGAR, BANGALORE' 'MALAD WEST, MUMBAI' 'VIKAS PURI, DELHI'
 'KONDAPUR, HYDERABAD' 'ANDHERI EAST, MUMBAI' 'SULUR, COIMBATORE'
 'ADYAR, CHENNAI' 'KRISHNA NAGAR, DELHI' 'LANGER HOUSE, HYDERABAD'
 'THIRUVANMIYUR, CHENNAI' 'DWARKA, DELHI' 'BHANDUP WEST, MUMBAI'
 'JANAK PURI, DELHI' 'RAJAJINAGAR, BANGALORE' 'SOUTH EXTENSION 1, DELHI'
 'KEMPS CORNER, MUMBAI' 'PEELAMEDU, COIMBATORE' 'KANDIVALI WEST, MUMBAI'
 'THEVARA, ERNAKULAM' 'WILSON GARDEN, BANGALORE' 'WADALA, MUMBAI'
 'PAHAR GANJ, DELHI' 'CHANCHALGUDA, HYDERABAD' 'CHIKKADPALLY, HYDERABAD'
 'PASUR-AVANASHI, COIMBATORE' 'NAGARBHAVI, BANGALORE'
 'LAJPAT NAGAR, DELHI' 'MAYUR VIHAR PH-I, DELHI' 'DILSHAD GARDEN, DELHI'
 'VIJAYANAGAR, BANGALORE' 'ALWARPET, CHENNAI'
 'PAPPANAMCODE, THIRUVANANTHAPURAM' 'ALUVA, ERNAKULAM'
 'NARIMAN POINT, MUMBAI' 'KILKATTALAI, CHENNAI' 'DILSUKHNAGAR, HYDERABAD'
 'KURLA WEST, MUMBAI' 'BEGUMPET, HYDERABAD' 'KALOOR, ERNAKULAM'
 'HITECH CITY, HYDERABAD' 'GOREGAON EAST, MUMBAI'
 'VELANDIPALAYAM, COIMBATORE' 'GHATKOPAR EAST, MUMBAI'
 'MULUND WEST, MUMBAI' 'YOUSUFGUDA, HYDERABAD' 'GHATKOPAR WEST, MUMBAI'
 'TVM BEACH, THIRUVANANTHAPURAM' 'VANAGARAM, CHENNAI' 'WORLI, MUMBAI'
 'KORAMANGALA 1 BLOCK, BANGALORE' 'SAKI VIHAR ROAD, MUMBAI'
 'VERSOVA, MUMBAI' 'CV RAMAN NAGAR, BANGALORE' 'SECUNDERABAD, HYDERABAD'
 'BTM LAYOUT 1ST STAGE, BANGALORE' 'RAMKOTI, HYDERABAD'
 'MRC NAGAR, CHENNAI' 'MALKAJGIRI, HYDERABAD' 'GACHIBOWLI, HYDERABAD'
 'MOGAPPAIR WEST, CHENNAI' 'MAYUR VIHAR PH-III, DELHI'
 'KURLA EAST, MUMBAI' 'ASHOK VIHAR, DELHI' 'MAHIM, MUMBAI'
 'VILLIVAKKAM, CHENNAI' 'SRINAGAR COLONY, HYDERABAD' 'CHROMEPET, CHENNAI'
 'PAMMAL, CHENNAI' 'BANASHANKARI, BANGALORE' 'VELACHERY, CHENNAI'
 'CHANAKYAPURI, DELHI' 'KALYAN NAGAR, BANGALORE' 'OSHIWARA, MUMBAI'
 'KARAPAKKAM, CHENNAI' 'BORIVALI, MUMBAI' 'MYLAPORE, CHENNAI'
 'ELECTRONICS CITY, BANGALORE' 'PERUNGUDI, CHENNAI'
 'BASAVANAGUDI, BANGALORE' 'MG ROAD, BANGALORE' 'THIRUVOTTIYUR, CHENNAI'
 'GREATER KAILASH PART 2, DELHI' 'BILEKAHALLI, BANGALORE'
 'NANGANALLUR, CHENNAI' 'ROHINI, DELHI' 'THRIKKAKARA, ERNAKULAM'
 'MANAPAKKAM, CHENNAI' 'BELLANDUR, BANGALORE' 'AMEERPET, HYDERABAD'
 'THIRUVALLOM, THIRUVANANTHAPURAM' 'R.S. PURAM, COIMBATORE'
 'KUMARAPURAM, THIRUVANANTHAPURAM' 'PALAM COLONY, DELHI' 'MANALI, CHENNAI'
 'VALASARAVAKKAM, CHENNAI' 'BARKATPURA, HYDERABAD'
 'SINGANALLUR, COIMBATORE' 'MULUND, MUMBAI' 'DADAR EAST, MUMBAI'
 'BORABANDA, HYDERABAD' 'MODEL TOWN 3, DELHI' 'ULSOOR, BANGALORE'
 'BHAYANDAR WEST, MUMBAI' 'HARI NAGAR, DELHI' 'HORAMAVU, BANGALORE'
 'SANTACRUZ EAST, MUMBAI' 'OMR ROAD, CHENNAI' 'KAMMANA HALLI, BANGALORE'
 'TILAK NAGAR, DELHI' 'PANATHUR, BANGALORE'
 'RAJARAJESHWARINAGAR, BANGALORE' 'PARAVUR, ERNAKULAM'
 'PREET VIHAR, DELHI' 'CHEMBUR EAST, MUMBAI' 'JAKKUR, BANGALORE'
 'VANASTHALIPURAM, HYDERABAD' 'MANDAVELI, CHENNAI'
 'KUMARA PARK WEST, BANGALORE' 'DOMLUR, BANGALORE'
 'JEEVANBHIMANAGAR, BANGALORE' 'SANTACRUZ WEST, MUMBAI'
 'SHANKAR VIHAR, DELHI' 'JOGESHWARI EAST, MUMBAI'
 'KASAVANAHALLI, BANGALORE' 'AMBALAMUKKU, THIRUVANANTHAPURAM'
 'JHILMIL COLONY, DELHI' 'DWARKA SECTOR 7, DELHI' 'TATABAD, COIMBATORE'
 'MARINE LINES, MUMBAI' 'TOLICHOWKI, HYDERABAD' 'SUNDARAPURAM, COIMBATORE'
 'KOTHANUR, BANGALORE' 'CHINMAYA NAGAR, CHENNAI' 'VASANT VIHAR, DELHI'
 'MEHDIPATNAM, HYDERABAD' 'KADUGODI, BANGALORE' 'GANAPATHY, COIMBATORE'
 'SR NAGAR, HYDERABAD' 'PERAMBUR, CHENNAI' 'OPERA HOUSE, MUMBAI'
 'SELVAPURAM, COIMBATORE' 'KARKARDOOMA, DELHI' 'ALWARTHIRUNAGAR, CHENNAI'
 'KR PURAM, BANGALORE' 'RAMESH NAGAR, DELHI' 'MALAKPET, HYDERABAD'
 'TONDIARPET, CHENNAI' 'VIKRAMPURI COLONY, HYDERABAD'
 'BESANT NAGAR, CHENNAI' 'VASANT KUNJ, DELHI' 'BANASWADI, BANGALORE'
 'BTM LAYOUT, BANGALORE' 'MEDAVAKKAM, CHENNAI' 'VILEPARLE WEST, MUMBAI'
 'SAHAKARANAGAR, BANGALORE' 'LB NAGAR, HYDERABAD' 'PUNJAGUTTA, HYDERABAD'
 'YAMUNA VIHAR, DELHI' 'MARATHAHALLI, BANGALORE'
 'JP NAGAR 2 PHASE, BANGALORE' 'RANI BAGH, DELHI' 'JAYAMAHAL, BANGALORE'
 'NAGPADA, MUMBAI' 'KUNDALAHALLI, BANGALORE' 'KAILASH COLONY, DELHI'
 'PANDAV NAGAR, DELHI' 'KARKHANA, HYDERABAD' 'WEST MAMBALAM, CHENNAI'
 'AMINJIKARAI, CHENNAI' 'MADIPAKKAM, CHENNAI' 'CHARKOP, MUMBAI'
 'ADARSH NAGAR, DELHI' 'DADAR, MUMBAI' 'KAGGADASAPURA, BANGALORE'
 'MATUNGA, MUMBAI' 'SUN CITY, HYDERABAD' 'MAHADEVAPURA, BANGALORE'
 'KALADY, ERNAKULAM' 'ANNA NAGAR WEST, CHENNAI' 'MAYUR VIHAR PH-II, DELHI'
 'TIS HAZARI, DELHI' 'VENNALA, ERNAKULAM' 'MIRA ROAD, MUMBAI'
 'ALWAL, HYDERABAD' 'TRIMULGHERRY, HYDERABAD'
 'RAJA ANNAMALAI PURAM, CHENNAI' 'JP NAGAR 7 PHASE, BANGALORE'
 'OLD BOWENPALLY, HYDERABAD' 'SANTOSH NAGAR, HYDERABAD'
 'HOPE COLLEGE, COIMBATORE' 'MULUND EAST, MUMBAI' 'MOUNT ROAD, CHENNAI'
 'PATEL NAGAR WEST, DELHI' 'JAYANAGAR 4 BLOCK, BANGALORE'
 'WEST MARREDPALLY, HYDERABAD' 'JAGRITI ENCLAVE, DELHI'
 'SARITA VIHAR, DELHI' 'RAJENDRA NAGAR, HYDERABAD'
 'THUDIYALUR, COIMBATORE' 'BHAYANDAR EAST, MUMBAI'
 'NARAYANGUDA, HYDERABAD' 'KOTHAPET, HYDERABAD' 'KK NAGAR, CHENNAI'
 'TRIPUNITHURA, ERNAKULAM' 'MODEL TOWN, DELHI'
 'SUCHITRA CIRCLE, HYDERABAD' 'PUSA ROAD, DELHI'
 'VIJAYNAGAR COLONY, HYDERABAD' 'ALANDUR, CHENNAI' 'CUFFE PARADE, MUMBAI'
 'KALKAJI, DELHI' 'SAIBABA COLONY, COIMBATORE'
 'KATTAKADA, THIRUVANANTHAPURAM' 'JOGESHWARI WEST, MUMBAI'
 'ERRAGADDA, HYDERABAD' 'TILAK NAGAR, HYDERABAD' 'EDAPALLY, ERNAKULAM'
 'PATPARGANJ, DELHI' 'SAINIKPURI, HYDERABAD' 'NANJUNDAPURAM, COIMBATORE'
 'NIZAMPET, HYDERABAD' 'KOLATHUR, CHENNAI' 'CHAMARAJPET, BANGALORE'
 'KALA GHODA, MUMBAI' 'PADMARAO NAGAR, HYDERABAD' 'UPPAL, HYDERABAD'
 'GUDUVANCHERY, CHENNAI' 'SATYA NIKETAN, DELHI' 'CHANDA NAGAR, HYDERABAD'
 'SOWRIPALAYAM, COIMBATORE' 'VIKHROLI WEST, MUMBAI'
 'RAJOURI GARDEN, DELHI' 'ALAKNANDA, DELHI' 'MILLERS ROAD, BANGALORE'
 'KANDANCHAVADI, CHENNAI' 'VIGYAN VIHAR, DELHI' 'BANDRA EAST, MUMBAI'
 'VILANKURICHI, COIMBATORE' 'MALAD EAST, MUMBAI' 'PRABHADEVI, MUMBAI'
 'ULLOOR, THIRUVANANTHAPURAM' 'RAJAKILPAKKAM, CHENNAI'
 'GREATER KAILASH, DELHI' 'MADINAGUDA, HYDERABAD' 'BORIVALI EAST, MUMBAI'
 'JUHU, MUMBAI' 'MUGALIVAKKAM, CHENNAI' 'HEBBAL, BANGALORE'
 'KIRTI NAGAR, DELHI' 'BALARAMAPURAM, THIRUVANANTHAPURAM'
 'BHANDUP EAST, MUMBAI' 'VV PURAM, BANGALORE' 'KILPAUK, CHENNAI'
 'JACOB CIRCLE, MUMBAI' 'SINGASANDRA, BANGALORE' 'KHAIRATABAD, HYDERABAD'
 'COIMBATORE AERODROME, COIMBATORE' 'J.C NAGAR, BANGALORE'
 'NARAINA VIHAR, DELHI' 'VIRUGAMBAKKAM, CHENNAI' 'RK PURAM, DELHI'
 'BANASHANKARI 1ST STAGE, BANGALORE' 'LAJPAT NAGAR 4, DELHI'
 'JAYANAGAR 5 BLOCK, BANGALORE' 'KALYANPURI, HYDERABAD'
 'TAMBARAM, CHENNAI' 'LAXMI NAGAR, DELHI' 'ANAND VIHAR, DELHI'
 'CHARNI ROAD, MUMBAI' 'PATEL NAGAR EAST, DELHI'
 'JAYANAGAR 9 BLOCK, BANGALORE' 'ECIL, HYDERABAD'
 'RAMAMURTHY NAGAR, BANGALORE' 'RAJ NAGAR - 2, DELHI'
 'CHUNABHATTI, MUMBAI' 'VIKHROLI EAST, MUMBAI' 'SHAKARPUR, DELHI'
 'SHAHDARA, DELHI' 'GOVANDI, MUMBAI' 'MIRA BHAYANDAR, MUMBAI'
 'DODDANEKUNDI, BANGALORE' 'MADHU VIHAR, DELHI' 'GUINDY, CHENNAI'
 'PALARIVATTOM, ERNAKULAM' 'CHARMINAR, HYDERABAD'
 'OLD AIRPORT ROAD, BANGALORE' 'SARJAPUR ROAD, BANGALORE' 'OKHLA, DELHI'
 'BAGHLINGAMPALLY, HYDERABAD' 'TROMBAY, MUMBAI' 'HRBR LAYOUT, BANGALORE'
 'FORT, MUMBAI' 'SHASTRI NAGAR, DELHI' 'RED HILLS, CHENNAI'
 'NEW BEL ROAD, BANGALORE' 'PARK TOWN, CHENNAI' 'FRAZER TOWN, BANGALORE'
 'FALAKNUMA, HYDERABAD' 'ROHINI SECTOR 7, DELHI' 'EAST OF KAILASH, DELHI'
 'CHINTADRIPET, CHENNAI' 'TAGORE GARDEN, DELHI' 'TRI NAGAR, DELHI'
 'MUTTADA, THIRUVANANTHAPURAM' 'MUNNEKOLLAL, BANGALORE'
 'TV MUSEUM, THIRUVANANTHAPURAM' 'SHIVALIK, DELHI' 'NEB SARAI, DELHI'
 'MAHALAKSHMI LAYOUT, BANGALORE' 'MANKHURD, MUMBAI' 'KAMLA NAGAR, DELHI'
 'SARAVANAMPATTI, COIMBATORE' 'SELAIYUR, CHENNAI' 'SALIGRAMAM, CHENNAI'
 'THIRUMULLAIVOYAL, CHENNAI' 'TEYNAMPET, CHENNAI' 'KOCHI, ERNAKULAM'
 'VIDYARANYAPURA, BANGALORE' 'MOGAPPAIR, CHENNAI' 'MAZGAON, MUMBAI'
 'SHIVAJI NAGAR, BANGALORE' 'JANGPURA, DELHI'
 'KAUDIAR SQUARE, THIRUVANANTHAPURAM' 'ARUMBAKKAM, CHENNAI'
 'CHERAI, ERNAKULAM' 'MIRA-BHAYANDAR ROAD, MUMBAI' 'RAM NAGAR, DELHI'
 'PAREL, MUMBAI' 'THANISANDRA, BANGALORE' 'PRAGATHI NAGAR, HYDERABAD'
 'KARAMANA, THIRUVANANTHAPURAM' 'AECS LAYOUT, BANGALORE'
 'NIZAMUDDIN EAST, DELHI' 'RAMANATHAPURAM, COIMBATORE'
 'ANNA NAGAR, CHENNAI' 'SHENOY NAGAR, CHENNAI' 'SIDDHAPUDUR, COIMBATORE'
 'KESHAV PURAM, DELHI' 'EDAKOCHI, ERNAKULAM' 'NAGAWARA, BANGALORE'
 'CHINTAL, HYDERABAD' 'MALVIYA NAGAR, DELHI' 'KARWAN, HYDERABAD'
 'VAZHAKULAM, ERNAKULAM' 'PMG JN, THIRUVANANTHAPURAM'
 'DWARKA SECTOR 6, DELHI' 'VIVEKNAGAR, BANGALORE' 'BALAPUR, HYDERABAD'
 'BANASHANKARI 2ND STAGE, BANGALORE' 'AZADPUR, DELHI' 'MOTI NAGAR, DELHI'
 'SAKINAKA, MUMBAI' 'THOPPUMPADY, ERNAKULAM' 'SANATH NAGAR, HYDERABAD'
 'ROYAPETTAH, CHENNAI' 'KORAMANGALA 5 BLOCK, BANGALORE'
 'KANJURMARG, MUMBAI' 'ERNAKULAM COLLEGE, ERNAKULAM' 'URAPAKKAM, CHENNAI'
 'COIMBATORE UKKADAM, COIMBATORE' 'SREEKARYAM, THIRUVANANTHAPURAM'
 'ERNAKULAM NORTH, ERNAKULAM' 'SULTANPUR, DELHI' 'BANERJI ROAD, ERNAKULAM'
 'BALKAMPET, HYDERABAD' 'KAVUNDAMPALAYAM, COIMBATORE'
 'KANCHANBAGH, HYDERABAD' 'PATEL NAGAR, DELHI' 'KILOKRI, DELHI'
 'HOODI, BANGALORE' 'NEW SEEMAPURI, DELHI' 'SESHADRIPURAM, BANGALORE'
 'VIJAYNAGAR, DELHI' 'BOWENPALLY, HYDERABAD' 'ONDIPUDUR, COIMBATORE'
 'TRIPLICANE, CHENNAI' 'RICHMOND TOWN, BANGALORE'
 'NEW RAJENDRA NAGAR, DELHI' 'JAHANGIRPURI, DELHI' 'VIVEK VIHAR, DELHI'
 'MALLESHPALYA, BANGALORE' 'PEZHAKKAPPILLY, ERNAKULAM'
 'LINGAMPALLY, HYDERABAD' 'JAMIA NAGAR, DELHI' 'BEGUM BAZAR, HYDERABAD'
 'LOWER PAREL, MUMBAI' 'ECR ROAD, CHENNAI' 'NANGLOI, DELHI'
 'CHINTALMET, HYDERABAD' 'WEST OF CHORD ROAD, BANGALORE' 'SV ROAD, MUMBAI'
 'JP NAGAR 5 PHASE, BANGALORE' 'SANJAY NAGAR, BANGALORE'
 'PANAMPILLY NAGAR, ERNAKULAM' 'DHARAVI, MUMBAI' 'ABBIGERE, BANGALORE'
 'MANACAUD, THIRUVANANTHAPURAM' 'POONAMALLE, CHENNAI' 'NAJAFGARH, DELHI'
 'UTTARAHALLI, BANGALORE' 'SEMBAKKAM, CHENNAI' 'TARNAKA, HYDERABAD'
 'NANDANAM, CHENNAI' 'SAIDAPET, CHENNAI' 'CHOOLAIMEDU, CHENNAI'
 'PERUNGALATHUR, CHENNAI' 'GULABI BAGH, DELHI' 'JASOLA, DELHI'
 'JP NAGAR 3 PHASE, BANGALORE' 'UPPILIPALAYAM, COIMBATORE'
 'SADASHIVANAGAR, BANGALORE' 'ROHINI SECTOR 24, DELHI'
 'MUVATTUPUZHA, ERNAKULAM' 'KHAN MARKET, DELHI' 'ABIDS, HYDERABAD'
 'GEETA COLONY, DELHI' 'MADANDAPURAM, CHENNAI' 'DWARKA SECTOR 22, DELHI'
 'GRANT ROAD, MUMBAI' 'JEEDIMETLA, HYDERABAD' 'TAMBARAM EAST, CHENNAI'
 'KOTHAGUDA, HYDERABAD' 'HAUZ KHAS, DELHI' 'HABSIGUDA, HYDERABAD'
 'BREACH CANDY, MUMBAI' 'VIDYANAGAR, BANGALORE' 'BEGUR, BANGALORE'
 'DAHISAR, MUMBAI' 'PACHALAM, ERNAKULAM' 'PERUMBAVOOR, ERNAKULAM'
 'AVADI, CHENNAI' 'COIMBATORE CENTRAL, COIMBATORE' 'LOKHANDWALA, MUMBAI'
 'TIRUVOTTIYUR, CHENNAI' 'ULLAL UPANAGARA, BANGALORE'
 'PERURKADA, THIRUVANANTHAPURAM' 'ASHOK VIHAR PHASE 3, DELHI'
 'WALKESHWAR, MUMBAI' 'SAIDABAD, HYDERABAD'
 'KORAMANGALA 6 BLOCK, BANGALORE' 'NEW ASHOK NAGAR, DELHI'
 'PEDDAR ROAD, MUMBAI' 'AYA NAGAR, DELHI' 'JP NAGAR, BANGALORE'
 'SASTHAMANGALAM, THIRUVANANTHAPURAM' 'YAKUTPURA, HYDERABAD'
 'SAMPANGIRAMNAGAR, BANGALORE' 'KASTURI NAGAR, BANGALORE'
 'PALLAVARAM, CHENNAI' 'MOTI BAGH, DELHI' 'MUKHERJEE NAGAR, DELHI'
 'BYCULLA, MUMBAI' 'PEERAGARHI, DELHI' 'AMBERPET, HYDERABAD'
 'JP NAGAR 6 PHASE, BANGALORE' 'SHOLINGANALLUR, CHENNAI'
 'LANGFORD ROAD, BANGALORE' 'CUMBALLA HILL, MUMBAI' 'COLABA, MUMBAI'
 'QUTAB INSTITUTIONAL AREA, DELHI' 'DOMMASANDRA, BANGALORE'
 'MALABAR HILL, MUMBAI' 'KORAMANGALA 8 BLOCK, BANGALORE'
 'ROHINI SECTOR 22, DELHI' 'LOTHKUNTA, HYDERABAD'
 'HAL 2ND STAGE, BANGALORE' 'JAYANAGAR 7 BLOCK, BANGALORE'
 'VADASSERIKONAM, THIRUVANANTHAPURAM' 'EAST MARREDPALLY, HYDERABAD'
 'KELAMBAKKAM, CHENNAI' 'CHINCHPOKLI, MUMBAI' 'DELHI CANTT, DELHI'
 'PADMANABHANAGAR, BANGALORE' 'SHEIKH SARAI, DELHI'
 'WASHERMENPET, CHENNAI' 'KONANAKUNTE, BANGALORE'
 'ASHOK VIHAR PHASE 1, DELHI' 'THIRUMALA, THIRUVANANTHAPURAM'
 'SARJAPURA, BANGALORE' 'JP NAGAR 1 PHASE, BANGALORE' 'JB NAGAR, MUMBAI'
 'PARUTHIPPARA, THIRUVANANTHAPURAM' 'VIKHROLI, MUMBAI'
 'JP NAGAR 8 PHASE, BANGALORE' 'GTB NAGAR, DELHI' 'VIDYANAGAR, HYDERABAD'
 'MASAB TANK, HYDERABAD' 'HAFEEZPET, HYDERABAD' 'JEEVAN PARK, DELHI'
 'DWARKA SECTOR 5, DELHI' 'CIVIL LINES, DELHI' 'ANAND NIKETAN, DELHI'
 'PAPPANAICKENPALAYAM, COIMBATORE' 'KOOVAPPADY, ERNAKULAM'
 'SRIRAMPURAM, BANGALORE' 'KORATTUR, CHENNAI'
 'PAPPANAICKENPUDUR, COIMBATORE' 'GANDHI NAGAR, DELHI'
 'VIGNAN NAGAR, BANGALORE' 'GANGANAGAR, BANGALORE' 'ELAMAKKARA, ERNAKULAM'
 'BODUPPAL, HYDERABAD' 'TILAK NAGAR, MUMBAI' 'KHETWADI, MUMBAI'
 'KENGERI, BANGALORE' 'SION EAST, MUMBAI' 'ROHINI SECTOR 6, DELHI'
 'KAZHAKUTTAM, THIRUVANANTHAPURAM' 'GOREGAON, MUMBAI'
 'PEROOR, THIRUVANANTHAPURAM' 'NEW THIPPASANDRA, BANGALORE'
 'JALAHALLI, BANGALORE' 'KING KOTI, HYDERABAD'
 'KALLAMBALAM, THIRUVANANTHAPURAM' 'DWARKA SECTOR 13, DELHI'
 'RESIDENCY ROAD, BANGALORE' 'RADHAKRISHNAN SALAI, CHENNAI'
 'HULIMAVU, BANGALORE' 'DASARAHALLI, BANGALORE' 'VILEPARLE, MUMBAI'
 'DELHI, DELHI' 'KACHIGUDA, HYDERABAD' 'VENKITAPURAM, COIMBATORE'
 'KUNIAMUTHUR, COIMBATORE' 'TV CHALAI, THIRUVANANTHAPURAM'
 'SERILINGAMPALLY, HYDERABAD' 'RMV 2ND STAGE, BANGALORE'
 'CHAMPAPET, HYDERABAD' 'SURYA NIKETAN, DELHI' 'KOVILPALAYAM, COIMBATORE'
 'NAMPALLY, HYDERABAD' 'SIDDAPURA, BANGALORE' 'NEREDMET, HYDERABAD'
 'VELLAKINAR, COIMBATORE' 'EGMORE, CHENNAI' 'KATWARIA SARAI, DELHI'
 'NAVALUR, CHENNAI' 'MEHRAULI, DELHI' 'HBR LAYOUT, BANGALORE'
 'SUBHASH NAGAR, DELHI' 'MALLEPALLY, HYDERABAD' 'EROOR SOUTH, ERNAKULAM'
 'LAJPAT NAGAR III, DELHI' 'KODUNGAIYUR, CHENNAI'
 'KUPPAKONANPUDUR, COIMBATORE' 'PARADISE, HYDERABAD'
 'ROHINI SECTOR 4, DELHI' 'KORAMANGALA 4 BLOCK, BANGALORE'
 'DWARKA SECTOR 3, DELHI' 'DURGA PURI, DELHI' 'KALAMASSERY, ERNAKULAM'
 'GULMOHAR PARK, DELHI' 'ADUGODI, BANGALORE' 'MOTI NAGAR, HYDERABAD'
 'NALLAGANDLA, HYDERABAD' 'GOWRIVAKKAM, CHENNAI' 'PERIYAR NAGAR, CHENNAI'
 'AUSTIN TOWN, BANGALORE' 'AFZALGUNJ, HYDERABAD'
 'COTTON HILL, THIRUVANANTHAPURAM' 'GOLDWINS, COIMBATORE'
 'KURAVANKONAM, THIRUVANANTHAPURAM' 'ROHINI SECTOR 3, DELHI'
 'LADO SARAI, DELHI' 'KORAMANGALA 2 BLOCK, BANGALORE' 'MADANGIR, DELHI'
 'MARINE DRIVE, MUMBAI' 'MARINE DRIVE, ERNAKULAM' 'ANGAMALY, ERNAKULAM'
 'NEELANKARAI, CHENNAI' 'CHURCHGATE, MUMBAI' 'KALAPATTI, COIMBATORE'
 'NAND NAGRI, DELHI' 'KANDIVALI, MUMBAI' 'MADANPURA, MUMBAI'
 'HEGDE NAGAR, BANGALORE' 'DOMALGUDA, HYDERABAD' 'MUMBAI CENTRAL, MUMBAI'
 'VASANTHNAGAR, BANGALORE' 'KAPASHERA, DELHI' 'AUGUST KRANTI MARG, DELHI'
 'KRISHNA NAGAR, HYDERABAD' 'LAL BAUG, MUMBAI'
 'PERUMATHURA, THIRUVANANTHAPURAM' 'MOLARBAND, DELHI' 'PIRAVOM, ERNAKULAM'
 'NEETI BAGH, DELHI' 'KISHANBAGH, HYDERABAD' 'SHANTINAGAR, BANGALORE'
 'POOJAPURA, THIRUVANANTHAPURAM' 'RATHINAPURI, COIMBATORE'
 'MODEL TOWN 1, DELHI' 'KOOTHATTUKULAM, ERNAKULAM' 'ANAND LOK, DELHI'
 'PAPPANAICKENPALAYAM WEST, COIMBATORE' 'SUBZI MANDI, DELHI'
 'SION, MUMBAI' 'NAGOLE, HYDERABAD' 'TVM PETTAH, THIRUVANANTHAPURAM'
 'CHANGAMPUZHA NAGAR, ERNAKULAM' 'PUZHAL, CHENNAI'
 'VANCHIYUR, THIRUVANANTHAPURAM' 'SUKH VIHAR, DELHI'
 'KOVALAM, THIRUVANANTHAPURAM' 'SWASTHYA VIHAR, DELHI' 'TARDEO, MUMBAI'
 'VISHNU GARDEN, DELHI' 'JAYANAGAR 1 BLOCK, BANGALORE'
 'SION KOLIWADA, MUMBAI' 'MAROL, MUMBAI' 'KALKERE, BANGALORE'
 'SINDHI COLONY, HYDERABAD' 'SILAMPUR, DELHI' 'VARTHUR, BANGALORE'
 'MODEL TOWN 2, DELHI' 'SURAJMAL VIHAR, DELHI' 'CHANDNI CHOWK, DELHI'
 'VEERAKERALAM, COIMBATORE' 'T DASARAHALLI, BANGALORE'
 'KAGGALIPURA, BANGALORE' 'THONNAKKAL, THIRUVANANTHAPURAM'
 'MANJAPRA, ERNAKULAM' 'YELLAREDDYGUDA, HYDERABAD'
 'KOVILAMBAKKAM, CHENNAI' 'BROADWAY, CHENNAI' 'PODANUR, COIMBATORE'
 'KOMPALLY, HYDERABAD' 'KOTTIVAKKAM, CHENNAI' 'MANSAROVER GARDEN, DELHI'
 'MANDAPESHWAR, MUMBAI' 'ROHINI SECTOR 15, DELHI' 'VADUTHALA, ERNAKULAM'
 'HEBBAL KEMPAPURA, BANGALORE' 'SITHALAPAKKAM, CHENNAI'
 'MKB NAGAR, CHENNAI' 'MG ROAD, HYDERABAD' 'DARYA GANJ, DELHI'
 'VENJARAMOODU, THIRUVANANTHAPURAM' 'KOTTURPURAM, CHENNAI'
 'RAMAPURAM, CHENNAI' 'KARMANGHAT, HYDERABAD' 'MOULA ALI, HYDERABAD'
 'NETAJI NAGAR, DELHI' 'CHANDRA LAYOUT, BANGALORE'
 'AKSHAYA NAGAR, BANGALORE' 'NIRMAN VIHAR, DELHI' 'VASANT ENCLAVE, DELHI'
 'ST THOMAS MOUNT, CHENNAI' 'ROYAPURAM, CHENNAI' 'ABHIRAMAPURAM, CHENNAI'
 'INDER PURI, DELHI' 'EDAYARPALAYAM, COIMBATORE' 'DEOLI, DELHI'
 'MULANTHURUTHY, ERNAKULAM' 'SUKHDEV VIHAR, DELHI' 'E'
 'KOTHAMANGALAM, ERNAKULAM' 'HARLUR, BANGALORE' 'BOLARUM, HYDERABAD'
 'RICHARDS TOWN, BANGALORE' 'NARELA, DELHI' 'NEHRU PLACE, DELHI'
 'RAMANTHAPUR, HYDERABAD' 'BALI NAGAR, DELHI' 'PALAVAKKAM, CHENNAI'
 'BALANAGAR, HYDERABAD' 'HYDERGUDA, HYDERABAD' 'CHERANNAGAR, COIMBATORE'
 'ROHINI SECTOR 11, DELHI' 'DWARKA SECTOR 4, DELHI'
 'PALLURUTHY, ERNAKULAM' 'VIZHINJAM, THIRUVANANTHAPURAM'
 'SANTACRUZ, MUMBAI' 'GANESH NAGAR, DELHI' 'VENGAL RAO NAGAR, HYDERABAD'
 'DEONAR, MUMBAI' 'EDAPALLY NORTH, ERNAKULAM' 'RED HILLS, HYDERABAD'
 'IDA JEEDIMETLA, HYDERABAD' 'METTUPALAYAM, COIMBATORE'
 'HAYATHNAGAR, HYDERABAD' 'KAKKANAD WEST, ERNAKULAM'
 'KHAJAGUDA, HYDERABAD' 'ROHINI SECTOR 5, DELHI' 'SARASWATI VIHAR, DELHI'
 'KINGSWAY CAMP, DELHI' 'RAMAMANGALAM, ERNAKULAM' 'INDIRAPURAM, DELHI'
 'PARASSALA, THIRUVANANTHAPURAM' 'CONNAUGHT PLACE, DELHI'
 'GOTTIGERRE, BANGALORE' 'SHIVRAMPALLY, HYDERABAD' 'VYASARPADI, CHENNAI'

In [14]:
places= list(df['Place'])


Locality=[]
City=[]

for i in places:
    try :
         Locality.append(i.split(',')[0].strip().upper())
    except :
         Locality.append('NONE')
    try :
         City.append(i.split(',')[1].strip().upper())
    except :
         City.append('NONE')

# appending NONE to Unique titles list
all_places.append('NONE')

Lets work on the experience column. This column has text which we need to split and get the integer data from the info.

We will be defining a function to extract the integer value and use the function for test and train data.

In [15]:
def changeexperience(x):
    bans=x.split(' ')
    return bans[0]

In [16]:
data['Experience']=data['Experience'].apply(changeexperience)
test['Experience']=test['Experience'].apply(changeexperience)
df['Experience']=df['Experience'].apply(changeexperience)

We will be dropping the Miscellaneous_Info column as the information in it is mostly utilized in different columns and also more than 50% of the data is missing values.

In [17]:
data.drop('Miscellaneous_Info',axis=1,inplace=True)
test.drop('Miscellaneous_Info',axis=1,inplace=True)
df.drop('Miscellaneous_Info',axis=1,inplace=True)

Lets work on the Ratings column. This column has numeric value with percentage symbol.

We will be creating a function to extract the numeric value from it and apply the same function to train and test data. 

Also, as we need to apply the function, we will be creating a temp data with no missing values and apply the same. 

Once we have the data, we will be filling the missing values with mean values for each profile type.

In [18]:
def removepercent(x):
    vans=x.split('%')
    return vans[0]

In [19]:
Rating_Values=data[data['Rating'].notnull()]
Rating_Values.head()

,Qualification,Experience,Rating,Place,Profile
0,"BHMS, MD - Homeopathy",24,100%,"Kakkanad, Ernakulam",Homeopath
1,"BAMS, MD - Ayurveda Medicine",12,98%,"Whitefield, Bangalore",Ayurveda
4,BAMS,20,100%,"Keelkattalai, Chennai",Ayurveda
7,BDS,10,99%,"Arekere, Bangalore",Dentist
12,"BDS, MDS",9,98%,"Coimbatore Racecourse, Coimbatore",Dentist

In [20]:
Rating_Values['Rating']=Rating_Values['Rating'].apply(removepercent)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [21]:
Rating_Values.head()

,Qualification,Experience,Rating,Place,Profile
0,"BHMS, MD - Homeopathy",24,100,"Kakkanad, Ernakulam",Homeopath
1,"BAMS, MD - Ayurveda Medicine",12,98,"Whitefield, Bangalore",Ayurveda
4,BAMS,20,100,"Keelkattalai, Chennai",Ayurveda
7,BDS,10,99,"Arekere, Bangalore",Dentist
12,"BDS, MDS",9,98,"Coimbatore Racecourse, Coimbatore",Dentist

In [22]:
Rating_Values['Rating']=Rating_Values['Rating'].astype(int)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [23]:
Rating_Values.groupby('Profile')['Rating'].mean()

Profile
Ayurveda            96.277108
Dentist             97.698454
Dermatologists      93.446281
ENT Specialist      88.973236
General Medicine    91.944238
Homeopath           96.524496
Name: Rating, dtype: float64

In [24]:
def fillratings(cols):
    Rating = cols[0]
    Profile = cols[1]
    
    if pd.isnull(Rating):

        if Profile == 'Ayurveda':
            return '96%'

        elif Profile == 'Dentist':
            return '98%'
        elif Profile=='Dermatologists':
            return '94%'
        elif Profile=='ENT Specialist':
            return '89%'
        elif Profile=='General Medicine':
            return '92%'
        elif Profile=='Homeopath':
            return '97%'
    else:
        return Rating

In [25]:
data['Rating']=data[['Rating','Profile']].apply(fillratings,axis=1)
df['Rating']=df[['Rating','Profile']].apply(fillratings,axis=1)
test['Rating']=test[['Rating','Profile']].apply(fillratings,axis=1)

In [26]:
df.isnull().sum()

Qualification     0
Experience        0
Rating            0
Place            25
Profile           0
Fees              0
dtype: int64

In [27]:
df.isnull().sum()

Qualification     0
Experience        0
Rating            0
Place            25
Profile           0
Fees              0
dtype: int64

In [28]:
df.shape

(5960, 6)

Now lets verify the profile column to see if any cell has more than one value.

In [29]:

Profile = list(data['Profile'])

# Finding Maximum number of Qualification mentioned in a single cell
maxim = 1
for i in Profile :
    if len(i.split(',')) > maxim:
         maxim = len(i.split(','))
         
print("\n\nMaximum Profile in a Cell : ", maxim)

Maximum Profile in a Cell :  1

Lets create a Train Dataset with all the modified and clean columns.

In [30]:
Train_Data = {}

Train_Data['Qualification1'] = Q1
Train_Data['Qualification2'] = Q2
Train_Data['Qualification3'] = Q3
Train_Data['Qualification4'] = Q4
Train_Data['Qualification5'] = Q5
Train_Data['Qualification6'] = Q6
Train_Data['Qualification7'] = Q7
Train_Data['Qualification8'] = Q8
Train_Data['Qualification9'] = Q9
Train_Data['Qualification10'] = Q10
Train_Data['Qualification11'] = Q11
Train_Data['Qualification12'] = Q12
Train_Data['Qualification13'] = Q13
Train_Data['Qualification14'] = Q14
Train_Data['Qualification15'] = Q15
Train_Data['Qualification16'] = Q16
Train_Data['Qualification17'] = Q17
Train_Data['LOCALITY'] = Locality
Train_Data['CITY'] = City
Train_Data['RATING'] = df["Rating"]
Train_Data['EXPERIENCE'] = df["Experience"]
Train_Data['PROFILE'] = df["Profile"]
Train_Data['FEES'] = df["Fees"]

Train_Data = pd.DataFrame(Train_Data)

In [31]:
Train_Data.head()

,CITY,EXPERIENCE,FEES,LOCALITY,PROFILE,Qualification1,Qualification10,Qualification11,Qualification12,Qualification13,...,Qualification17,Qualification2,Qualification3,Qualification4,Qualification5,Qualification6,Qualification7,Qualification8,Qualification9,RATING
0,ERNAKULAM,24,100,KAKKANAD,Homeopath,BHMS,NONE,NONE,NONE,NONE,...,NONE,MD - HOMEOPATHY,NONE,NONE,NONE,NONE,NONE,NONE,NONE,100%
1,BANGALORE,12,350,WHITEFIELD,Ayurveda,BAMS,NONE,NONE,NONE,NONE,...,NONE,MD - AYURVEDA MEDICINE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,98%
2,BANGALORE,9,300,MATHIKERE - BEL,ENT Specialist,MBBS,NONE,NONE,NONE,NONE,...,NONE,MS - OTORHINOLARYNGOLOGY,NONE,NONE,NONE,NONE,NONE,NONE,NONE,89%
3,BANGALORE,12,250,BANNERGHATTA ROAD,Ayurveda,BSC - ZOOLOGY,NONE,NONE,NONE,NONE,...,NONE,BAMS,NONE,NONE,NONE,NONE,NONE,NONE,NONE,96%
4,CHENNAI,20,250,KEELKATTALAI,Ayurveda,BAMS,NONE,NONE,NONE,NONE,...,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,100%

In [32]:
Train_Data['RATING']=Train_Data['RATING'].apply(removepercent)
Train_Data['RATING']=Train_Data['RATING'].astype(int)
Train_Data['EXPERIENCE']=Train_Data['EXPERIENCE'].astype(int)

In [33]:
Train_Data.head()

,CITY,EXPERIENCE,FEES,LOCALITY,PROFILE,Qualification1,Qualification10,Qualification11,Qualification12,Qualification13,...,Qualification17,Qualification2,Qualification3,Qualification4,Qualification5,Qualification6,Qualification7,Qualification8,Qualification9,RATING
0,ERNAKULAM,24,100,KAKKANAD,Homeopath,BHMS,NONE,NONE,NONE,NONE,...,NONE,MD - HOMEOPATHY,NONE,NONE,NONE,NONE,NONE,NONE,NONE,100
1,BANGALORE,12,350,WHITEFIELD,Ayurveda,BAMS,NONE,NONE,NONE,NONE,...,NONE,MD - AYURVEDA MEDICINE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,98
2,BANGALORE,9,300,MATHIKERE - BEL,ENT Specialist,MBBS,NONE,NONE,NONE,NONE,...,NONE,MS - OTORHINOLARYNGOLOGY,NONE,NONE,NONE,NONE,NONE,NONE,NONE,89
3,BANGALORE,12,250,BANNERGHATTA ROAD,Ayurveda,BSC - ZOOLOGY,NONE,NONE,NONE,NONE,...,NONE,BAMS,NONE,NONE,NONE,NONE,NONE,NONE,NONE,96
4,CHENNAI,20,250,KEELKATTALAI,Ayurveda,BAMS,NONE,NONE,NONE,NONE,...,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,100

Now lest perform the same on Test data

In [34]:
Qualification = list(test['Qualification'])

Q1 = []
Q2 = []
Q3 = []
Q4 = []
Q5 = []
Q6 = []
Q7 = []
Q8 = []
Q9 = []
Q10 = []
Q11 = []
Q12 = []
Q13 = []
Q14 = []
Q15 = []
Q16 = []
Q17 = []


for i in Qualification:
        try :
            Q1.append(i.split(',')[0].strip().upper())
        except :
            Q1.append('NONE')
        try :
            Q2.append(i.split(',')[1].strip().upper())
        except :
            Q2.append('NONE')
        try :
            Q3.append(i.split(',')[2].strip().upper())
        except :
            Q3.append('NONE')
        try :
            Q4.append(i.split(',')[3].strip().upper())
        except :
            Q4.append('NONE')
        try :
            Q5.append(i.split(',')[4].strip().upper())
        except :
            Q5.append('NONE')
        try :
            Q6.append(i.split(',')[5].strip().upper())
        except :
            Q6.append('NONE')
        try :
            Q7.append(i.split(',')[6].strip().upper())
        except :
            Q7.append('NONE')
        try :
            Q8.append(i.split(',')[7].strip().upper())
        except :
            Q8.append('NONE')
        try :
            Q9.append(i.split(',')[8].strip().upper())
        except :
            Q9.append('NONE')    
        try :
            Q10.append(i.split(',')[9].strip().upper())
        except :
            Q10.append('NONE')
        try :
            Q11.append(i.split(',')[10].strip().upper())
        except :
            Q11.append('NONE')
        try :
            Q12.append(i.split(',')[11].strip().upper())
        except :
            Q12.append('NONE')
        try :
            Q13.append(i.split(',')[12].strip().upper())
        except :
            Q13.append('NONE')
        try :
            Q14.append(i.split(',')[13].strip().upper())
        except :
            Q14.append('NONE')
        try :
            Q15.append(i.split(',')[14].strip().upper())
        except :
            Q15.append('NONE')
        try :
            Q16.append(i.split(',')[15].strip().upper())
        except :
            Q16.append('NONE')
        try :
            Q17.append(i.split(',')[16].strip().upper())
        except :
            Q17.append('NONE')

In [35]:
places= list(test['Place'])


Locality=[]
City=[]

for i in places:
    try :
         Locality.append(i.split(',')[0].strip().upper())
    except :
         Locality.append('NONE')
    try :
         City.append(i.split(',')[1].strip().upper())
    except :
         City.append('NONE')

In [36]:
test['Rating']=test['Rating'].apply(removepercent)
test['Rating']=test['Rating'].astype(int)
test['Experience']=test['Experience'].astype(int)

In [37]:
Test_Data = {}

Test_Data['Qualification1'] = Q1
Test_Data['Qualification2'] = Q2
Test_Data['Qualification3'] = Q3
Test_Data['Qualification4'] = Q4
Test_Data['Qualification5'] = Q5
Test_Data['Qualification6'] = Q6
Test_Data['Qualification7'] = Q7
Test_Data['Qualification8'] = Q8
Test_Data['Qualification9'] = Q9
Test_Data['Qualification10'] = Q10
Test_Data['Qualification11'] = Q11
Test_Data['Qualification12'] = Q12
Test_Data['Qualification13'] = Q13
Test_Data['Qualification14'] = Q14
Test_Data['Qualification15'] = Q15
Test_Data['Qualification16'] = Q16
Test_Data['Qualification17'] = Q17
Test_Data['LOCALITY'] = Locality
Test_Data['CITY'] = City
Test_Data['RATING'] = test["Rating"]
Test_Data['EXPERIENCE'] = test["Experience"]
Test_Data['PROFILE'] = test["Profile"]

Test_Data = pd.DataFrame(Test_Data)

Now we need to label encode the categorical values.

We will be first combining the test and train data to use the label encoding.

In [38]:
all_cities=[]
all_localities=[]
all_profile=[]
all_cities = [Train_Data[['CITY']], Test_Data[['CITY']]]
all_localities = [Train_Data[['LOCALITY']], Test_Data[['LOCALITY']]]
all_profile=[Train_Data[['PROFILE']], Test_Data[['PROFILE']]]
all_cities = pd.concat(all_cities)
all_localities = pd.concat(all_localities)
all_profile = pd.concat(all_profile)

In [39]:
le_qualification = LabelEncoder()
le_profile = LabelEncoder()

le_city = LabelEncoder()

le_locality = LabelEncoder()


le_qualification.fit(all_qualification)
le_profile.fit(all_profile)

le_city.fit(all_cities)
le_locality.fit(all_localities)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\preprocessing\label.py:95: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LabelEncoder()

In [40]:
Train_Data.isnull().values.any()

False

In [41]:
Test_Data.isnull().values.any()

False

In [42]:
Train_Data['Qualification1'] = le_qualification.transform(Train_Data['Qualification1'])
Train_Data['Qualification2'] = le_qualification.transform(Train_Data['Qualification2'])
Train_Data['Qualification3'] = le_qualification.transform(Train_Data['Qualification3'])
Train_Data['Qualification4'] = le_qualification.transform(Train_Data['Qualification4'])
Train_Data['Qualification5'] = le_qualification.transform(Train_Data['Qualification5'])
Train_Data['Qualification6'] = le_qualification.transform(Train_Data['Qualification6'])
Train_Data['Qualification7'] = le_qualification.transform(Train_Data['Qualification7'])
Train_Data['Qualification8'] = le_qualification.transform(Train_Data['Qualification8'])
Train_Data['Qualification9'] = le_qualification.transform(Train_Data['Qualification9'])
Train_Data['Qualification10'] = le_qualification.transform(Train_Data['Qualification10'])
Train_Data['Qualification11'] = le_qualification.transform(Train_Data['Qualification11'])
Train_Data['Qualification12'] = le_qualification.transform(Train_Data['Qualification12'])
Train_Data['Qualification13'] = le_qualification.transform(Train_Data['Qualification13'])
Train_Data['Qualification14'] = le_qualification.transform(Train_Data['Qualification14'])
Train_Data['Qualification15'] = le_qualification.transform(Train_Data['Qualification15'])
Train_Data['Qualification16'] = le_qualification.transform(Train_Data['Qualification16'])
Train_Data['Qualification17'] = le_qualification.transform(Train_Data['Qualification17'])
Train_Data['LOCALITY'] = le_locality.transform(Train_Data['LOCALITY'])
Train_Data['CITY'] = le_city.transform(Train_Data['CITY'])
Train_Data['PROFILE'] = le_profile.transform(Train_Data['PROFILE'])

In [43]:
Test_Data['Qualification1'] = le_qualification.transform(Test_Data['Qualification1'])
Test_Data['Qualification2'] = le_qualification.transform(Test_Data['Qualification2'])
Test_Data['Qualification3'] = le_qualification.transform(Test_Data['Qualification3'])
Test_Data['Qualification4'] = le_qualification.transform(Test_Data['Qualification4'])
Test_Data['Qualification5'] = le_qualification.transform(Test_Data['Qualification5'])
Test_Data['Qualification6'] = le_qualification.transform(Test_Data['Qualification6'])
Test_Data['Qualification7'] = le_qualification.transform(Test_Data['Qualification7'])
Test_Data['Qualification8'] = le_qualification.transform(Test_Data['Qualification8'])
Test_Data['Qualification9'] = le_qualification.transform(Test_Data['Qualification9'])
Test_Data['Qualification10'] = le_qualification.transform(Test_Data['Qualification10'])
Test_Data['Qualification11'] = le_qualification.transform(Test_Data['Qualification11'])
Test_Data['Qualification12'] = le_qualification.transform(Test_Data['Qualification12'])
Test_Data['Qualification13'] = le_qualification.transform(Test_Data['Qualification13'])
Test_Data['Qualification14'] = le_qualification.transform(Test_Data['Qualification14'])
Test_Data['Qualification15'] = le_qualification.transform(Test_Data['Qualification15'])
Test_Data['Qualification16'] = le_qualification.transform(Test_Data['Qualification16'])
Test_Data['Qualification17'] = le_qualification.transform(Test_Data['Qualification17'])
Test_Data['LOCALITY'] = le_locality.transform(Test_Data['LOCALITY'])
Test_Data['CITY'] = le_city.transform(Test_Data['CITY'])
Test_Data['PROFILE'] = le_profile.transform(Test_Data['PROFILE'])

In [44]:
# Classifying Independent and Dependent Features
#_______________________________________________

# Dependent Variable
Y_train = Train_Data['FEES']

# Independent Variables
X_train = Train_Data.drop(['FEES'], axis = 1)

# Independent Variables for Test Set
X_test = Test_Data.iloc[:,:].values
Y_test=[]

Now lets use Random Forest

In [45]:
m = RandomForestClassifier(n_jobs=2,random_state=1)
m.fit(X_train,Y_train)
m.score(X_train,Y_train)

0.9765100671140939

Decision Tree Classifier

In [50]:
dt = DecisionTreeClassifier(random_state = 0 , max_depth = 5)
dt.fit(X_train , Y_train)
dt.score(X_train , Y_train)

0.2966442953020134

As we can see the Random Forest has an accuracy of 97.65 which is pretty good for the model. In order to avoid overfitting or underfitting we will be hypertuning our model using Grid searchCV.

In [51]:
m.predict(X_test)

array([150, 300,  50, ..., 100, 250, 200], dtype=int64)

In [52]:
estimator = RandomForestRegressor()
param_grid = { "n_estimators" :[50,100,200] ,
               "max_features" : ["auto", "sqrt", "log2"] ,
               "bootstrap": [True, False] ,
               "min_samples_split" : [2,4,8]
             }
clf = GridSearchCV(estimator, param_grid, cv=5)
clf.fit(X_train,Y_train)
print(f"best parameters: {clf.best_params_}")
print(f"best score: {clf.score(X_train,Y_train)}")

best parameters: {'bootstrap': True, 'max_features': 'log2', 'min_samples_split': 8, 'n_estimators': 100}
best score: 0.65022174131293

In [53]:
#Saving the best model for future use

from sklearn.externals import joblib
joblib.dump(clf,'Doctor Fee Prediction.obj')

['Doctor Fee Prediction.obj']